---
- name: "Check if {{ m_simplesamlphp_path }} exists"
  stat:
    path: "{{ m_simplesamlphp_path }}"
  register: simplesamlphp_exists

- name: Remove Extension:SimpleSamlAuth, Meza now uses Extension:SimpleSAMLphp
  file:
    path: "{{ m_mediawiki }}/extensions/SimpleSamlAuth"
    state: absent

- name: "Check if SAML MW extension exists"
  stat:
    path: "{{ m_mediawiki }}/extensions/SimpleSAMLphp"
  register: simplesamlextension_exists

- name: Ensure good permissions on simplesamlphp directory and subs (if dir exists)
  file:
    path: "{{ m_simplesamlphp_path }}"
    owner: "{{ m_simplesamlphp_owner }}"
    group: "{{ m_simplesamlphp_group }}"
    mode: "{{ m_simplesamlphp_mode }}"
    recurse: true
  when: simplesamlphp_exists.stat.exists and simplesamlphp_exists.stat.isdir

- name: Ensure good permissions on Extension:SimpleSAMLphp directory and subs (if dir exists)
  file:
    path: "{{ m_mediawiki }}/extensions/SimpleSAMLphp"
    mode: "{{ m_htdocs_mode }}"
    owner: "{{ m_htdocs_owner }}"
    group: "{{ m_htdocs_group }}"
    recurse: true
  when: simplesamlphp_exists.stat.exists and simplesamlphp_exists.stat.isdir

- name: Get simplesamlphp tarball
  become: true
  become_user: "meza-ansible"
  get_url:
    url: "https://github.com/simplesamlphp/simplesamlphp/releases/download/v{{ simplesamlphp_version }}/simplesamlphp-{{ simplesamlphp_version }}.tar.gz"
    dest: "{{ m_home }}/meza-ansible/"
  register: new_simplesamlphp_archive

- name: Remove simplesamlphp directory if new version available
  file:
    path: "{{ m_simplesamlphp_path }}"
    state: absent
  when: new_simplesamlphp_archive.changed

# Do this check again now in case the above command removed the directory, but something went
# wrong and it was never created (script crashed). Without this check the deploy could be put
# in a state where it might never recreate SimpleSamlPhp
- name: "Check if {{ m_simplesamlphp_path }} exists again"
  stat:
    path: "{{ m_simplesamlphp_path }}"
  register: simplesamlphp_exists2

- name: "Create empty directory for {{ m_simplesamlphp_path }} if installing new version"
  file:
    path: "{{ m_simplesamlphp_path }}"
    state: directory
    owner: "{{ m_simplesamlphp_owner }}"
    group: "{{ m_simplesamlphp_group }}"
    mode: "{{ m_simplesamlphp_mode }}"
  when: not simplesamlphp_exists.stat.exists

- name: Unarchive simplesamlphp tarball if new
  become: true
  unarchive:
    src: "{{ m_home }}/meza-ansible/simplesamlphp-{{ simplesamlphp_version }}.tar.gz"
    dest: "{{ m_simplesamlphp_path }}"
    owner: "{{ m_simplesamlphp_owner }}"
    group: "{{ m_simplesamlphp_group }}"
    mode: "{{ m_simplesamlphp_mode }}"
    remote_src: true
    extra_opts:
      - "--strip-components=1"
  when: not simplesamlphp_exists.stat.exists or new_simplesamlphp_archive.changed

- name: Ensure Extension:PluggableAuth installed
  become: true
  become_user: "meza-ansible"
  # Ref #1149 for TMPDIR environment var
  environment:
    TMPDIR: "{{ m_tmp }}"
  git:
    repo: https://github.com/wikimedia/mediawiki-extensions-PluggableAuth.git
    dest: "{{ m_mediawiki }}/extensions/PluggableAuth"
    version: "tags/6.3" # "{{ saml_mw_extension_version }}"
    umask: "0002"
  tags:
    - latest

- name: Ensure Extension:SimpleSAMLphp (MediaWiki extension) installed
  become: true
  become_user: "meza-ansible"
  # Ref #1149 for TMPDIR environment var
  environment:
    TMPDIR: "{{ m_tmp }}"
  git:
    repo: https://github.com/wikimedia/mediawiki-extensions-SimpleSAMLphp.git
    dest: "{{ m_mediawiki }}/extensions/SimpleSAMLphp"
    version: "tags/5.0.1" # "{{ saml_mw_extension_version }}"
    umask: "0002"
  tags:
    - latest

- name: Ensure ./config directory in place
  file:
    path: "{{ m_simplesamlphp_path }}/config"
    state: directory

- name: Ensure ./metadata directory in place
  file:
    path: "{{ m_simplesamlphp_path }}/metadata"
    state: directory

- name: Ensure config files in place
  template:
    src: "{{ item.filename }}.j2"
    dest: "{{ item.dest_path }}/{{ item.filename }}"
  with_items:
    # Config files for SimpleSamlPhp (PHP SAML library)
    - filename: "config.php"
      dest_path: "{{ m_simplesamlphp_path }}/config"
    - filename: "saml20-idp-remote.php"
      dest_path: "{{ m_simplesamlphp_path }}/metadata"
    - filename: "authsources.php"
      dest_path: "{{ m_simplesamlphp_path }}/config"

    # Config files for SimpleSamlAuth (MediaWiki extension)
    - filename: "samlLocalSettings.php"
      dest_path: "{{ m_deploy }}"

    # Config file used by MW extension + any other PHP app needing auth
    # (landing page, admin functions, etc)
    - filename: "SAMLConfig.php"
      dest_path: "{{ m_deploy }}"

- name: Ensure _still_ good permissions on simplesamlphp directory and subs
  file:
    path: "{{ m_simplesamlphp_path }}"
    owner: "{{ m_simplesamlphp_owner }}"
    group: "{{ m_simplesamlphp_group }}"
    mode: "{{ m_simplesamlphp_mode }}"
    recurse: true

- name: Ensure _still_ good permissions on Extension:SimpleSamlAuth directory and subs
  file:
    path: "{{ m_mediawiki }}/extensions/SimpleSamlAuth"
    mode: "{{ m_htdocs_mode }}"
    owner: "{{ m_htdocs_owner }}"
    group: "{{ m_htdocs_group }}"
    recurse: true

- name: Ensure NonMediaWikiSimpleSamlAuth.php in place
  template:
    src: NonMediaWikiSimpleSamlAuth.php.j2
    dest: "{{ m_htdocs }}/NonMediaWikiSimpleSamlAuth.php"
    owner: meza-ansible
    group: apache
    mode: 0755
